#!/usr/bin/env python3
"""
bootstrap_county.py — Xcerebro County Intelligence Framework

Bounded bootstrap script. Creates the run-folder scaffolding for a new county
build. It does NOT build scrapers, adapters, dashboards, databases, or run
recon. It only sets up the directory + launch file so Claude Code can execute
Phase 0 against a clean scope.

Authorized for autonomous execution by Claude Code on first run, per
MASTER_PROMPT.md Section 4.5 (Autonomous First-Run Rule).

Usage:
    python scaffold/bootstrap_county.py \\
        --county "Bexar County" \\
        --state "Texas" \\
        --slug bexar_tx \\
        --phase phase0

Outputs created:
    runs/<county_slug>/
    runs/<county_slug>/LAUNCH_<COUNTY_SLUG_UPPER>.md

Outputs NOT created (intentionally — these belong to later phases):
    config/counties/<county_slug>.json   (Phase 0 produces this)
    data/                                 (Phase 1+ produce these)
    scrapers/                             (Phase 2+ produce these)

Copyright (c) 2026 Xcerebro LLC. All rights reserved.
Proprietary VIP license. See LICENSE.md.
"""

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


# Slug validation: lowercase letters, digits, underscores. Two-letter state suffix
# strongly recommended but not enforced (some operators may use a different
# convention).
SLUG_PATTERN = re.compile(r"^[a-z0-9_]+$")

# Phase scope values. Bootstrap currently only supports phase0; future versions
# may add phase1 etc.
SUPPORTED_PHASES = ("phase0",)

# Framework version stamp — must match FRAMEWORK_VERSION.json. Updated here
# so generated launch files record which framework version produced them.
FRAMEWORK_VERSION = "v5.1.2-beta-r3"


def parse_args(argv):
    """Parse command-line arguments. Returns argparse.Namespace."""
    parser = argparse.ArgumentParser(
        prog="bootstrap_county.py",
        description=(
            "Create the run-folder scaffolding for a new county build. "
            "Phase 0 only. Does not build scrapers, dashboards, or databases."
        ),
    )
    parser.add_argument(
        "--county",
        required=True,
        help="County name with the word 'County' included. Example: 'Bexar County'",
    )
    parser.add_argument(
        "--state",
        required=True,
        help="Full state name. Example: 'Texas'",
    )
    parser.add_argument(
        "--slug",
        required=True,
        help="County slug. Lowercase, underscore-separated. Example: 'bexar_tx'",
    )
    parser.add_argument(
        "--phase",
        default="phase0",
        choices=SUPPORTED_PHASES,
        help="Phase scope. Currently only phase0 is supported.",
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help=(
            "Path to framework repo root. Defaults to the parent of scaffold/. "
            "Use this only for testing the bootstrap script from a temp folder."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be created without writing files.",
    )
    return parser.parse_args(argv)


def validate_slug(slug):
    """Validate the slug format. Returns (ok, error_message)."""
    if not slug:
        return False, "slug is empty"
    if not SLUG_PATTERN.match(slug):
        return False, (
            f"slug '{slug}' contains invalid characters. "
            f"Use lowercase letters, digits, and underscores only. "
            f"Examples: bexar_tx, harris_tx, maricopa_az"
        )
    if slug.startswith("_") or slug.endswith("_"):
        return False, f"slug '{slug}' cannot start or end with an underscore"
    if "__" in slug:
        return False, f"slug '{slug}' cannot contain consecutive underscores"
    return True, None


def resolve_repo_root(explicit_root):
    """Determine the repo root. Returns Path."""
    if explicit_root:
        return Path(explicit_root).resolve()
    # Default: assume this script lives at <repo>/scaffold/bootstrap_county.py
    script_path = Path(__file__).resolve()
    return script_path.parent.parent


def generate_launch_file_content(county, state, slug, phase):
    """Generate the LAUNCH_<SLUG>.md content. Returns string."""
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    slug_upper = slug.upper()
    return f"""# Launch: {county}, {state} — {phase.upper()} only

Generated by `scaffold/bootstrap_county.py` on {now_iso}.
Framework version: {FRAMEWORK_VERSION}

This launch document is a county-specific scoping override. It does NOT replace
MASTER_PROMPT.md. MASTER_PROMPT.md is the framework contract. Follow it exactly.

## Target

- County: {county}, {state}
- Slug: {slug}
- Target config file: config/counties/{slug}.json
- Run folder: runs/{slug}/
- Phase scope: {phase}

## Scope — {phase.upper()} ONLY (Recon Mode)

This is **Recon Mode** (MASTER_PROMPT.md Section 4.6). Run Phase 0 (County Source
Recon and Onboarding Gate) as defined in MASTER_PROMPT.md. Stop when Phase 0
completes the Build Eligibility Gate (Section 4.10). Do NOT enter Build Mode
without explicit operator authorization.

Do NOT in this run:

- Build scrapers
- Build adapters
- Build dashboards
- Create Supabase tables
- Touch GitHub Pages
- Proceed to portal fingerprinting (Build Mode only)
- Proceed to Phase 1 (synthetic harness — Build Mode)
- Patch framework files (knowledge_base/, scaffold/,
  config/counties/_schema.json, config/counties/_template.json,
  MASTER_PROMPT.md, README.md, MIGRATION.md, START_HERE.md, LICENSE.md,
  FRAMEWORK_VERSION.json, .gitignore)

## Five-Layer Source Verification Gate (MASTER_PROMPT Section 4.7)

For every source in the source-category checklist, walk Layers 1–5:

1. **Official origin verification** — verified_from_url, verification_method
2. **Source category verification** — records_available, search_fields
3. **Data access verification** — access_method, public_access_status, document_access_status
4. **Lead value and source role verification** — source_role (PRIMARY_LEAD_SOURCE / SUPPORTING / ENRICHMENT / REFERENCE_ONLY / BLOCKED / NOT_FOUND), lead_value
5. **Portal proof verification** — sample_record_path_confirmed, sample_record_type, sample_search_possible, sample_document_view_possible, verification_confidence

Record every result in the source's proof packet (the 18 v5.0.0 fields). The
schema enforces population. A source block missing required proof packet fields
fails Phase 0 validation.

## Product rule — official event source-driven lead intelligence

This framework is an OFFICIAL EVENT SOURCE-DRIVEN lead intelligence system.

LEADS come from EVENT-BASED / DISTRESS-BASED sources (Tier 1):

- Clerk records, recorder records
- Court filings (foreclosure, probate, civil judgments, evictions)
- Foreclosure filings, sheriff sale records
- Tax delinquency events, tax sale events
- Probate records, liens, judgments, lis pendens, recorded notices
- Code enforcement events (when they expose violations / liens / demolition /
  condemnation / nuisance)
- Demolition events, condemnation events

SUPPORTING (Tier 2) — strengthens leads but cannot create them:

- Court case detail pages, document images, auction details, sale status,
  probate metadata, judgment details

ENRICHMENT ONLY (Tier 3, NEVER treated as leads):

- Parcel data, GIS data, CAD data, assessor data
- Owner mailing data, tax roll data, bulk property records
- Valuation, beds, baths, year built, equity estimate, absentee, vacancy

If no verified primary event source is accessible in {county} (clerk, recorder,
court portal, district clerk, sheriff, tax office, tax collector, trustee sale
portal, foreclosure listing portal, tax lien foreclosure listing, auction
vendor, official vendor portal, or posted notices page), mark it blocked, record
the blocker and next_access_strategy in the source proof packet, and stop after
the Build Eligibility Gate. Clerk and recorder are the most common primary
sources but not the only valid ones. Do NOT compensate by filling the dashboard
with enrichment data. A parcel viewer is not a lead intelligence build.

## Phase 0.5 — Auto-Resolve Blockers (MASTER_PROMPT Section 4.14 — v5.1.0-beta+)

If Phase 0 surfaces blocked, ambiguous, dead, wrong-category, or access-constrained
primary lead sources, run Phase 0.5 BEFORE producing the final verdict.

Phase 0.5 flow:

1. For each source with `verification_confidence` LOW/BLOCKED or `source_role`
   BLOCKED_SOURCE, classify the blocker (`blocker_type`)
2. Technical blockers — auto-resolve. Permission blockers — record requirement and stop attempting.
3. Attempt resolution strategies in the approved order (Section 4.14):
   find_official_vendor_link → replace_homepage_with_record_portal →
   discover_public_search_endpoint → inspect_network_requests →
   discover_hidden_api → use_playwright → use_session_cookie → use_seeded_session →
   (cost-gated) use_captcha_solver / use_stealth_browser / use_residential_proxy →
   (credential-gated) use_operator_login / request_free_account /
   use_paid_subscription_if_operator_provides → manual_operator_assisted_pull →
   standing_records_delivery → public_records_request_last_resort → mark_not_available
4. Record every attempt in `auto_resolve_attempts` array on the source
5. Update source's `auto_resolve_status` and `final_resolution_status`
6. Update top-level `auto_resolve_status` and `final_resolution_status`
7. Recompute `build_verdict` — may upgrade to AUTO_RESOLVED_READY_TO_BUILD,
   PARTIALLY_RESOLVED_BUILDABLE, or downgrade to AUTO_RESOLVE_FAILED

Cost gating: before attempting paid/credential paths (steps 9-14 in the strategy list),
check `estimated_cost_category`. FREE/LOW proceeds. MEDIUM/HIGH/UNKNOWN requires operator approval.

Public records request is never the default. It is a final last resort.

## Phase 0 Step 4 — Write the populated county config (v5.1.1-beta+)

**Locked rule:** the populated county config MUST be written via
`scaffold/ops/write_county_config.py`, NOT via Claude Code's text-streaming
Write tool. See MASTER_PROMPT.md Section 4.28 for the full rule.

Required flow:

1. Build the full config as a Python dict in memory.
2. Call `write_county_config(config_dict, target_path, schema_path)`.
3. Print the returned `WriteResult.summary()` block to the operator.
4. If `status` is `JSON_INVALID` or `SCHEMA_INVALID`, attempt exactly ONE
   structured repair (re-build the dict, call the same writer). If the
   second attempt also fails, write `runs/{slug}/CONFIG_WRITE_FAILED.md`
   and stop. Do NOT proceed to the Build Mode Approval Gate. Do NOT fall
   back to text-streaming JSON.

If `jsonschema` is not installed locally, the writer reports
`SCHEMA_VALIDATION_SKIPPED`. This is graceful — JSON syntax validation
still passed and the config is still written. The framework does not
auto-install `jsonschema`.

## Phase label enforcement (MASTER_PROMPT Section 4.29 — v5.1.1-beta+)

Claude Code MUST emit these labeled phrases on their own lines during this
Phase 0 run:

- `PHASE 0 STARTING`
- `PHASE 0 STEP 1 — INSPECT`
- `PHASE 0 STEP 2 — RECON`
- `PHASE 0 STEP 3 — VERIFICATION GATE`
- `PHASE 0 COMPLETE`
- `PHASE 0.5 STARTING — AUTO-RESOLVE BLOCKERS` (or `PHASE 0.5 SKIPPED — NO BLOCKERS`)
- `PHASE 0.5 COMPLETE`
- `PHASE 0 STEP 4 — WRITE CONFIG, VERDICT, MANIFEST`
- `BUILD MODE APPROVAL GATE`

These are scrollback anchors so an operator watching a long autonomous run
always knows where they are. They are not decorative.

## Operator knowledge capture (MASTER_PROMPT Section 4.30 — v5.1.1-beta+)

Operator-volunteered knowledge during this run goes to one of two channels:

- **Schema-level overrides** that change framework behavior (confidence
  upgrade, access permission change, build authorization) go in the
  `operator_override_audit` array of `config/counties/{slug}.json`.
- **Casual contextual knowledge** (portal quirks, refresh cadence
  observations, login workflow notes, paid-tier evaluations, personnel
  contacts, manual-pull tricks) goes in `runs/{slug}/operator_notes.md`
  under a section heading for the relevant source ID (or `## general` if
  it applies broadly).

The bootstrap script has already created an empty `operator_notes.md`
template in this run folder. Claude Code MUST append to it as
operator-volunteered knowledge surfaces during Phase 0. Do NOT treat
operator knowledge as casual chat that disappears at the end of the
conversation.

## Build Mode Approval Gate (MASTER_PROMPT Section 4.15 — v5.1.0-beta+)

After Phase 0 + Phase 0.5 complete, STOP and ask the operator before entering Build Mode.

Build Mode (do not start without explicit "yes"): portal fingerprinting, scraper adapter
selection, scraper building, normalization, enrichment, dashboard, heartbeat, deployment,
scheduler, production verification.

Approval prompt format:

```
Phase 0 and Phase 0.5 are complete.

Build verdict: <build_verdict>

Summary:
- <one line per primary source: status + accessibility>
- <one line on enrichment sources>
- <one line on blocked sources awaiting operator action>

Build label if approved: <FULL_BUILD | PARTIAL_BUILD | SOURCE_LIMITED | PRIMARY_SOURCE_PENDING>

Do you want me to enter Build Mode <with these sources / with the accessible primary source only / not yet>?
```

Wait for explicit "yes proceed" / "proceed partial" / "stop." Implicit approval is NOT accepted.

## Build Eligibility Gate (MASTER_PROMPT Section 4.10)

At the end of Phase 0 (or Phase 0.5 if blockers were attempted), set the top-level fields in `config/counties/{slug}.json`:

- `build_verdict` — one of: READY_TO_BUILD, READY_WITH_BLOCKERS, RECON_ONLY,
  WAITING_ON_ACCESS, NOT_BUILDABLE_YET, AUTO_RESOLVED_READY_TO_BUILD,
  PARTIALLY_RESOLVED_BUILDABLE, AUTO_RESOLVE_FAILED
- `build_verdict_reason` — plain English explanation
- `build_verdict_at` — ISO 8601 timestamp
- `auto_resolve_status` — overall county auto-resolve outcome
- `final_resolution_status` — final resolution category

Build Mode does not start unless verdict is READY_TO_BUILD, AUTO_RESOLVED_READY_TO_BUILD,
or PARTIALLY_RESOLVED_BUILDABLE AND the operator explicitly approves.

## Do Not Proceed Matrix (MASTER_PROMPT Section 4.11)

Phase 0 stops (with a clean verdict, not a failure) if any of these fire:

1. No verified primary event source found
2. No primary lead source verified
3. Only enrichment sources found
4. All P0 sources are blocked
5. County config fails schema validation
6. Portal proof missing for required P0 sources
7. Dashboard would contain zero event-based leads
8. Only available data is parcel / GIS / CAD / assessor / tax roll / bulk property
9. Source access requires paid subscription or login AND no operator credential declared
10. System cannot verify public access to records or document images
11. No required P0 source reached verification_confidence HIGH/MEDIUM AND no operator_override

## Environment caveat

The Python environment in this repo may not be fully bootstrapped on first run.
If `python scaffold/tests/run_all.py` fails with `python not found` or
`module not found`, report this as an ENVIRONMENT SETUP ISSUE in the change
manifest. Do NOT treat it as a framework failure. Do NOT bypass the test by
patching it.

If the test runs and fails on assertion errors, that IS a framework /
county-config issue and should be reported as such.

## Closing requirement — VIP-friendly Phase 0 verdict + change manifest

When Phase 0 stops, the final output must include BOTH:

### (1) The plain-English verdict message (MASTER_PROMPT Section 4.12)

```
Phase 0 completed.

County build verdict: <BUILD_VERDICT>

Reason:
- <plain English statement about each P0 source>
- <plain English statement about enrichment availability>
- <plain English statement about why this verdict was chosen>

Recommended next action:
<one-sentence recommendation in operator language>
```

### (2) The change manifest

1. Files created
2. Files modified
3. Source URLs added (grouped by official_status / source_role)
4. Sources flagged UNVERIFIED with reasons
5. Sources flagged NOT_FOUND with reasons
6. Sources flagged BLOCKED_SOURCE with next_access_strategy
7. Any operator_override fields set to true (and why)
8. Open questions for the operator
9. Build Eligibility Gate result (build_verdict, build_verdict_reason)
10. Do Not Proceed Matrix conditions that fired (if any)
11. Schema validation result (pass/fail, errors if any)
12. Framework gate result (`python scaffold/tests/run_all.py`) — pass/fail/environment-blocked
13. Confirmation that no framework files outside `config/counties/{slug}.json` and `runs/{slug}/` were modified

## Start now

Begin with Phase 0 Step 1: Inspect. Output the repo inventory before making
any edits. Then proceed through Phase 0 Steps 2-4 per MASTER_PROMPT.md, applying
the 5-layer Source Verification Gate to every source category.

When Phase 0 completes, print the VIP-friendly verdict message AND the change
manifest, then STOP. Do not start Phase 1 unless the operator explicitly says:
"Proceed to Phase 1."
"""


def generate_operator_notes_template(county, state, slug):
    """Generate the empty operator_notes.md template (v5.1.1-beta+).

    Returns string. The template is human-readable markdown with section
    placeholders for each kind of operator-volunteered knowledge.
    """
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""# Operator notes — {county}, {state}

Generated by `scaffold/bootstrap_county.py` on {now_iso}.
Framework version: {FRAMEWORK_VERSION}

This file captures operator-volunteered knowledge during Phase 0 that does
NOT rise to the level of a schema-recorded operator override. It is a
contextual companion to `config/counties/{slug}.json`, not a
schema-validated artifact.

See MASTER_PROMPT.md Section 4.30 for the rule. Two channels with a clean
separation of concerns:

- **`operator_override_audit`** (in the county config JSON) — records
  every operator override that CHANGES what the framework is allowed
  to do.
- **`operator_notes.md`** (this file) — records CASUAL operator
  knowledge that doesn't change framework behavior but is worth
  keeping for context.

Claude Code MUST append to this file during Phase 0 as operator
knowledge surfaces. Each entry should be:

- Timestamped with ISO 8601 UTC
- Under a section heading for the relevant source ID (or `## general`)
- Briefly summarized in Claude Code's own words

## general

(notes that apply across all sources for this county build)

## <source_id>

(populated by Claude Code as operator knowledge surfaces during Phase 0)
"""


def create_run_folder(repo_root, slug, county, state, phase, dry_run=False):
    """Create runs/<slug>/, runs/<slug>/LAUNCH_<SLUG>.md, and
    runs/<slug>/operator_notes.md.

    Returns (success, paths_created, error_message).
    """
    run_folder = repo_root / "runs" / slug
    launch_file_name = f"LAUNCH_{slug.upper()}.md"
    launch_file = run_folder / launch_file_name
    operator_notes_file = run_folder / "operator_notes.md"

    paths = {
        "run_folder": run_folder,
        "launch_file": launch_file,
        "operator_notes_file": operator_notes_file,
    }

    if dry_run:
        return True, paths, None

    # Check if anything already exists
    if launch_file.exists():
        return False, paths, (
            f"Launch file already exists at {launch_file}. "
            f"Refusing to overwrite. Delete it manually if you want to regenerate, "
            f"or pick a different slug."
        )

    try:
        run_folder.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        return False, paths, f"Failed to create {run_folder}: {exc}"

    try:
        content = generate_launch_file_content(county, state, slug, phase)
        launch_file.write_text(content, encoding="utf-8", newline="\n")
    except OSError as exc:
        return False, paths, f"Failed to write {launch_file}: {exc}"

    # v5.1.1-beta+: create empty operator_notes.md template
    if not operator_notes_file.exists():
        try:
            notes_content = generate_operator_notes_template(county, state, slug)
            operator_notes_file.write_text(
                notes_content, encoding="utf-8", newline="\n"
            )
        except OSError as exc:
            return False, paths, (
                f"Failed to write {operator_notes_file}: {exc}"
            )

    return True, paths, None


def main(argv=None):
    """Entry point. Returns 0 on success, non-zero on failure."""
    args = parse_args(argv if argv is not None else sys.argv[1:])

    # Validate slug
    ok, err = validate_slug(args.slug)
    if not ok:
        print(f"ERROR: {err}", file=sys.stderr)
        return 2

    # Sanity-check that --county includes the word 'County'. We don't enforce
    # this rigidly because some jurisdictions use 'Parish' (Louisiana) or
    # 'Borough' (Alaska, NY). But we surface a warning so the operator sees it.
    county_lower = args.county.lower()
    expected_suffixes = ("county", "parish", "borough", "city", "municipality")
    if not any(s in county_lower for s in expected_suffixes):
        print(
            f"WARNING: --county value '{args.county}' does not appear to include "
            f"a jurisdiction suffix (County, Parish, Borough, City, Municipality). "
            f"Continuing anyway.",
            file=sys.stderr,
        )

    # Resolve repo root
    repo_root = resolve_repo_root(args.repo_root)
    if not repo_root.exists():
        print(f"ERROR: Repo root does not exist: {repo_root}", file=sys.stderr)
        return 2
    if not (repo_root / "MASTER_PROMPT.md").exists():
        print(
            f"ERROR: {repo_root} does not look like a framework repo "
            f"(no MASTER_PROMPT.md found). Use --repo-root to point at the "
            f"framework directory.",
            file=sys.stderr,
        )
        return 2

    # Create the run folder + launch file
    success, paths, error = create_run_folder(
        repo_root=repo_root,
        slug=args.slug,
        county=args.county,
        state=args.state,
        phase=args.phase,
        dry_run=args.dry_run,
    )

    if not success:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    # Report
    if args.dry_run:
        print(f"[DRY RUN] Would create:")
    else:
        print(f"Bootstrap complete for {args.county}, {args.state}:")
    print(f"  - Run folder: {paths['run_folder']}")
    print(f"  - Launch file: {paths['launch_file']}")
    print(f"  - Operator notes file: {paths['operator_notes_file']}")
    print()
    print(f"Next step — paste this into Claude Code:")
    print()
    print(
        f"  Read MASTER_PROMPT.md and {paths['launch_file'].relative_to(repo_root)}. "
        f"Run {args.phase} only."
    )
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
